project:
  type: book
  resources:
    - "/assets/*.png"
    - "/assets/*.glb"

book:
  title: "Getting Started"
  author: "David G. Oppenheimer"
  date: "10/2/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - software-needed.qmd
    - rstudio.qmd
    - gromacs-tutorial.qmd
    - scratch-pad.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti         #  spacelab or yeti
    css: styles.css
    toc: true
    toc-location: right
engine: knitr
date: last-modified
date-format: iso


